// Prints an .env.local for the local stack: anon + service_role JWTs signed with the local secret.
import crypto from "node:crypto";

const secret = process.env.LOCAL_JWT_SECRET;
if (!secret) throw new Error("LOCAL_JWT_SECRET is required");
const b64 = (o) => Buffer.from(JSON.stringify(o)).toString("base64url");
const sign = (payload) => {
  const head = b64({ alg: "HS256", typ: "JWT" });
  const body = b64(payload);
  return `${head}.${body}.${crypto.createHmac("sha256", secret).update(`${head}.${body}`).digest("base64url")}`;
};
const exp = Math.floor(Date.now() / 1000) + 10 * 365 * 24 * 3600;
console.log(`# Generated by scripts/local-stack for LOCAL testing only.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${sign({ role: "anon", iss: "supabase", exp })}
NEXT_PUBLIC_SITE_URL=http://localhost:3000
SUPABASE_SECRET_KEY=${sign({ role: "service_role", iss: "supabase", exp })}
CRON_SECRET=local-cron-secret`);
